[package]
name = "osmpoi-cli"
version = "0.1.0"
authors = ["Xubai Wang <kindredwekingwang@gmail.com>"]
edition = "2018"

[[bin]]
name = "osmpoi"
path = "src/main.rs"

[dependencies]
osmpoi = { path = "../../osmpoi/" }
clap = "3.0.0-beta.2"
anyhow = "1.0.38"
dirs = "3.0.1"
