[package]
name = "osmpoi"
version = "0.1.0"
authors = ["Xubai Wang <kindredwekingwang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.5"
osmpbfreader = "0.14.0"
rusqlite = "0.24.2"
