[package]
name = "osmpoi"
version = "0.1.0"
authors = ["Xubai Wang <kindredwekingwang@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.2.1"
itertools = "0.10.5"
osmpbfreader = "0.16.0"
serde_json = "1.0.96"
signal-hook = "0.3.15"
