name: osmpoi-cli

on:
  push:
    paths:
      - 'ui/osmpoi-cli/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --manifest-path ui/osmpoi-cli/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path ui/osmpoi-cli/Cargo.toml --verbose
